# Generated by Django 4.1.3 on 2022-11-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_pw', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=10)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
