# Generated by Django 4.1.3 on 2022-11-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
    ]
